name: appbase_client
description: "A new Flutter project."
# description: "i built the way i like ðŸ˜Š."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ensure Dart 3 or higher for hive_ce

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # State Management
  flutter_riverpod: ^2.5.1 

  # Networking & Services
  http: ^1.2.1
  url_launcher: ^6.2.6

  # Caching - UPDATED TO HIVE CE
  hive_ce: ^2.14.0
  hive_ce_flutter: ^2.3.2
  path_provider: ^2.1.3

  # UI & Markdown
  flutter_markdown: ^0.7.1
  cached_network_image: ^3.3.1
  share_plus: ^12.0.0
  go_router: ^16.2.4
  flutter_cache_manager: ^3.3.1
  shared_preferences: ^2.2.3 
  intl: ^0.19.0
  new_version_plus: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
  # Code Generation -
  hive_ce_generator: ^1.9.5
  build_runner: ^2.4.9
  
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  change_app_package_name: ^1.1.0 

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/icon_launcher.png"
  android: true
  ios: true
  web:
    generate: true

flutter_native_splash:
  color: "#121212"
  image: assets/images/icon_launcher.png
  android: true
  ios: true
  web: true